require 'spank/component.rb'
require 'spank/container.rb'
require 'spank/interceptor_registration.rb'
require 'spank/invocation.rb'
require 'spank/ioc.rb'
require 'spank/lambda_behaviours.rb'
require 'spank/proxy.rb'
